// spec_decode.go implements speculative decoding for 2-3x faster token generation.
//
// HOW IT WORKS:
//   1. A small "draft" model (e.g. 0.5B-1B params) generates N candidate tokens fast
//   2. The large "target" model verifies all N candidates in ONE batch forward pass
//   3. Accepted tokens are free -- they cost nothing on the target model
//   4. On mismatch, we revert to the target model's token and discard the rest
//
// SPEEDUP: If the draft model predicts correctly 60-80% of the time (common for
// code completion, structured output, or continuation), you get ~2x throughput
// because you're generating 5 tokens for the cost of ~2 target model passes.
//
// WHEN TO USE:
//   - Draft and target must share the same vocabulary (same tokenizer)
//   - Best for same-family models: Qwen-0.5B drafting for Qwen-14B
//   - Predictable tasks (code, JSON, templates) get higher acceptance rates
//
// WHEN NOT TO USE:
//   - Draft model from different family (vocab mismatch = garbage)
//   - Creative writing (low acceptance rate negates the speedup)
//   - If VRAM can't hold both models simultaneously
package torch

import (
	"fmt"
	"math"
	"math/rand"
	"sync"
	"time"

	"github.com/David2024patton/iTaKTorchQ4/pkg/torch/llama"
)

// SpeculativeDecoder manages draft-target model pairs for speculative decoding.
type SpeculativeDecoder struct {
	mu sync.Mutex

	// Draft model resources.
	draftModel   llama.Model
	draftCtx     llama.Context
	draftVocab   llama.Vocab
	draftSampler llama.Sampler

	// Target model resources (the main engine model).
	targetModel   llama.Model
	targetCtx     llama.Context
	targetVocab   llama.Vocab
	targetSampler llama.Sampler
	targetNVocab  int

	// Configuration.
	nDraft   int     // number of speculative tokens per step (default: 5)
	pAccept  float64 // minimum acceptance probability threshold

	// Statistics.
	Stats SpecStats
}

// SpecStats tracks speculative decoding performance metrics.
type SpecStats struct {
	TotalDraftTokens    int64         // total tokens generated by draft model
	AcceptedTokens      int64         // tokens accepted from draft model
	RejectedTokens      int64         // tokens rejected (target disagreed)
	TotalSteps          int64         // number of speculative decode steps
	AvgAcceptanceRate   float64       // running average acceptance rate
	AvgTokensPerStep    float64       // average accepted tokens per step
	TotalTimeDraft      time.Duration // time spent in draft model
	TotalTimeVerify     time.Duration // time spent in target verification
	SpeedupEstimate     float64       // estimated speedup factor vs sequential
}

// NewSpeculativeDecoder creates a new speculative decoder.
//
// Parameters:
//   - targetModel/targetCtx: the main (large) model and its context
//   - draftModelPath: path to the small draft model GGUF file
//   - nDraft: how many tokens the draft model predicts ahead (5 is typical)
//   - draftGPULayers: GPU layers for the draft model (0 = CPU, 999 = all GPU)
//   - threads: CPU threads for the draft model
func NewSpeculativeDecoder(
	targetModel llama.Model,
	targetCtx llama.Context,
	draftModelPath string,
	nDraft int,
	draftGPULayers int,
	threads int,
) (*SpeculativeDecoder, error) {
	if targetModel == 0 || targetCtx == 0 {
		return nil, fmt.Errorf("target model/context required")
	}
	if draftModelPath == "" {
		return nil, fmt.Errorf("draft model path required")
	}
	if nDraft <= 0 {
		nDraft = 5
	}
	if threads <= 0 {
		threads = 4
	}

	// Load the draft model.
	draftParams := llama.ModelDefaultParams()
	draftParams.NGpuLayers = int32(draftGPULayers)
	draftParams.UseMmap = 1

	draftModel, err := llama.ModelLoadFromFile(draftModelPath, draftParams)
	if err != nil {
		return nil, fmt.Errorf("load draft model: %w", err)
	}

	// Verify vocab compatibility (critical for speculative decoding).
	targetVocab := llama.ModelGetVocab(targetModel)
	draftVocab := llama.ModelGetVocab(draftModel)

	targetVocabSize := llama.VocabNTokens(targetVocab)
	draftVocabSize := llama.VocabNTokens(draftVocab)

	if targetVocabSize != draftVocabSize {
		llama.ModelFree(draftModel)
		return nil, fmt.Errorf("vocab mismatch: target has %d tokens, draft has %d -- models must share the same tokenizer",
			targetVocabSize, draftVocabSize)
	}

	// Create context for draft model (smaller context is fine).
	draftCtxParams := llama.ContextDefaultParams()
	draftCtxParams.NCtx = 4096 // draft doesn't need huge context
	draftCtxParams.NThreads = int32(threads)
	draftCtxParams.NThreadsBatch = int32(threads)
	draftCtxParams.NBatch = 512
	// Use q8_0 KV cache for draft too (saves VRAM).
	draftCtxParams.TypeK = llama.GGMLTypeQ8_0
	draftCtxParams.TypeV = llama.GGMLTypeQ8_0

	draftCtx, err := llama.InitFromModel(draftModel, draftCtxParams)
	if err != nil {
		llama.ModelFree(draftModel)
		return nil, fmt.Errorf("create draft context: %w", err)
	}

	// Create samplers for both models.
	targetSampler := llama.NewSampler(targetModel, llama.DefaultSamplers, llama.DefaultSamplerParams())
	draftSampler := llama.NewSampler(draftModel, llama.DefaultSamplers, llama.DefaultSamplerParams())

	fmt.Printf("[iTaK Torch] Speculative decoding enabled: draft=%s n_draft=%d\n", draftModelPath, nDraft)
	fmt.Printf("[iTaK Torch] Draft vocab: %d tokens, Target vocab: %d tokens (match: OK)\n",
		draftVocabSize, targetVocabSize)

	return &SpeculativeDecoder{
		draftModel:    draftModel,
		draftCtx:      draftCtx,
		draftVocab:    draftVocab,
		draftSampler:  draftSampler,
		targetModel:   targetModel,
		targetCtx:     targetCtx,
		targetVocab:   targetVocab,
		targetSampler: targetSampler,
		targetNVocab:  int(targetVocabSize),
		nDraft:        nDraft,
		pAccept:       0.0, // accept all valid tokens
	}, nil
}

// DecodeStep performs one speculative decoding step:
//   1. Draft model generates nDraft candidate tokens
//   2. Target model verifies them all in one batch
//   3. Returns accepted tokens (possibly more than 1)
//
// The pos parameter is the current position in the sequence.
// prevToken is the last accepted token.
// Returns the accepted tokens and any error.
func (sd *SpeculativeDecoder) DecodeStep(pos int, prevToken llama.Token) ([]llama.Token, error) {
	sd.mu.Lock()
	defer sd.mu.Unlock()

	sd.Stats.TotalSteps++

	// Step 1: Draft model generates N candidate tokens.
	draftStart := time.Now()
	draftTokens, draftLogProbs, err := sd.generateDraftTokens(pos, prevToken)
	if err != nil {
		return nil, fmt.Errorf("draft generation: %w", err)
	}
	sd.Stats.TotalTimeDraft += time.Since(draftStart)
	sd.Stats.TotalDraftTokens += int64(len(draftTokens))

	// Step 2: Target model verifies all candidates in ONE forward pass.
	verifyStart := time.Now()
	accepted, err := sd.verifyTokens(pos, prevToken, draftTokens, draftLogProbs)
	if err != nil {
		return nil, fmt.Errorf("verification: %w", err)
	}
	sd.Stats.TotalTimeVerify += time.Since(verifyStart)

	// Step 3: Update statistics.
	nAccepted := len(accepted)
	sd.Stats.AcceptedTokens += int64(nAccepted)
	sd.Stats.RejectedTokens += int64(len(draftTokens) - nAccepted)

	if sd.Stats.TotalSteps > 0 {
		sd.Stats.AvgAcceptanceRate = float64(sd.Stats.AcceptedTokens) / float64(sd.Stats.TotalDraftTokens)
		sd.Stats.AvgTokensPerStep = float64(sd.Stats.AcceptedTokens) / float64(sd.Stats.TotalSteps)
	}

	// Estimate speedup.
	if sd.Stats.TotalTimeVerify > 0 {
		draftRatio := float64(sd.Stats.TotalTimeDraft) / float64(sd.Stats.TotalTimeDraft+sd.Stats.TotalTimeVerify)
		sd.Stats.SpeedupEstimate = sd.Stats.AvgTokensPerStep / (1.0 + draftRatio)
	}

	return accepted, nil
}

// generateDraftTokens runs the draft model to produce N candidate tokens.
func (sd *SpeculativeDecoder) generateDraftTokens(pos int, prevToken llama.Token) ([]llama.Token, []float64, error) {
	tokens := make([]llama.Token, 0, sd.nDraft)
	logProbs := make([]float64, 0, sd.nDraft)

	currentToken := prevToken
	currentPos := pos

	for i := 0; i < sd.nDraft; i++ {
		if err := sd.decodeSingle(sd.draftCtx, currentToken, currentPos); err != nil {
			break // draft failure is non-fatal, just return fewer candidates
		}

		// Sample next token from draft model.
		nextToken := llama.SamplerSample(sd.draftSampler, sd.draftCtx, -1)
		llama.SamplerAccept(sd.draftSampler, nextToken)

		// Get the log probability of this token.
		logProb := sd.getLogProb(sd.draftCtx, nextToken)

		tokens = append(tokens, nextToken)
		logProbs = append(logProbs, logProb)
		currentToken = nextToken
		currentPos++

		// Stop if we hit EOS.
		if llama.VocabIsEOG(sd.draftVocab, nextToken) {
			break
		}
	}

	return tokens, logProbs, nil
}

// verifyTokens runs the target model to verify draft candidates.
// Uses rejection sampling: accept if target probability >= draft probability.
func (sd *SpeculativeDecoder) verifyTokens(pos int, prevToken llama.Token, draftTokens []llama.Token, draftLogProbs []float64) ([]llama.Token, error) {
	if len(draftTokens) == 0 {
		return nil, nil
	}

	// Decode the full sequence on the target model.
	verifyTokens := make([]llama.Token, 0, len(draftTokens)+1)
	verifyTokens = append(verifyTokens, prevToken)
	verifyTokens = append(verifyTokens, draftTokens...)

	for i, tok := range verifyTokens {
		if err := sd.decodeSingle(sd.targetCtx, tok, pos+i); err != nil {
			return nil, err
		}
	}

	// Verify each draft token using rejection sampling.
	accepted := make([]llama.Token, 0, len(draftTokens))

	for i, draftToken := range draftTokens {
		targetLogProb := sd.getLogProb(sd.targetCtx, draftToken)

		// Rejection sampling: accept with probability min(1, p_target / p_draft).
		acceptProb := math.Exp(targetLogProb - draftLogProbs[i])
		if acceptProb >= 1.0 || rand.Float64() < acceptProb {
			accepted = append(accepted, draftToken)
			llama.SamplerAccept(sd.targetSampler, draftToken)
		} else {
			// Reject: sample from target model instead and stop.
			targetToken := llama.SamplerSample(sd.targetSampler, sd.targetCtx, int32(i))
			llama.SamplerAccept(sd.targetSampler, targetToken)
			accepted = append(accepted, targetToken)
			break
		}
	}

	// If all draft tokens accepted, sample one bonus token from target.
	if len(accepted) == len(draftTokens) {
		bonusToken := llama.SamplerSample(sd.targetSampler, sd.targetCtx, int32(len(draftTokens)))
		llama.SamplerAccept(sd.targetSampler, bonusToken)
		accepted = append(accepted, bonusToken)
	}

	return accepted, nil
}

// decodeSingle decodes a single token at the given position.
func (sd *SpeculativeDecoder) decodeSingle(ctx llama.Context, token llama.Token, pos int) error {
	batch := llama.BatchGetOne([]llama.Token{token})
	_, err := llama.Decode(ctx, batch)
	return err
}

// getLogProb extracts the log-probability of a token from the model's logits.
func (sd *SpeculativeDecoder) getLogProb(ctx llama.Context, token llama.Token) float64 {
	logits, err := llama.GetLogits(ctx, 1, sd.targetNVocab)
	if err != nil || logits == nil || len(logits) == 0 {
		return 0.0
	}

	tokenLogit := logits[int(token)]

	// Compute log-softmax for numerical stability.
	maxLogit := float32(math.Inf(-1))
	for _, l := range logits {
		if l > maxLogit {
			maxLogit = l
		}
	}

	sumExp := float64(0)
	for _, l := range logits {
		sumExp += math.Exp(float64(l - maxLogit))
	}

	logProb := float64(tokenLogit-maxLogit) - math.Log(sumExp)
	return logProb
}

// Close releases all draft model resources.
func (sd *SpeculativeDecoder) Close() {
	sd.mu.Lock()
	defer sd.mu.Unlock()

	if sd.draftSampler != 0 {
		llama.SamplerFree(sd.draftSampler)
		sd.draftSampler = 0
	}
	if sd.targetSampler != 0 {
		llama.SamplerFree(sd.targetSampler)
		sd.targetSampler = 0
	}
	if sd.draftCtx != 0 {
		llama.Free(sd.draftCtx)
		sd.draftCtx = 0
	}
	if sd.draftModel != 0 {
		llama.ModelFree(sd.draftModel)
		sd.draftModel = 0
	}

	fmt.Printf("[iTaK Torch] Speculative decoder closed. Stats: %d steps, %.1f%% acceptance, ~%.1fx speedup\n",
		sd.Stats.TotalSteps, sd.Stats.AvgAcceptanceRate*100, sd.Stats.SpeedupEstimate)
}

// IsEnabled returns true if speculative decoding is active.
func (sd *SpeculativeDecoder) IsEnabled() bool {
	return sd != nil && sd.draftModel != 0
}

// ResetStats resets the performance counters.
func (sd *SpeculativeDecoder) ResetStats() {
	sd.mu.Lock()
	defer sd.mu.Unlock()
	sd.Stats = SpecStats{}
}
